/*
 * Copyright © 2020-2022, Matjaž Guštin <dev@matjaz.it>
 * <https://matjaz.it>. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Neither the name of nor the names of its contributors may be used to
 *    endorse or promote products derived from this software without specific
 *    prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS “AS IS”
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * @file
 * @internal
 * Tests of the hzl_ClientBuildRequest() function.
 *
 * @warning
 * REDUCING COVERAGE ON PURPOSE. NOT implementing all the testcases for all possible incorrect
 * content of the context, because they have already been checked for the hzl_ClientInit()
 * function and the inner checks are exactly the same, performed by the same internal
 * function hzl_ClientCheckCtxPointers().
 */

#include "hzlTest.h"

static void
hzlClientTest_ClientBuildRequestMsgToTxMustNotBeNull(void)
{
    hzl_Err_t err;

    err = hzl_ClientBuildRequest(NULL, NULL, 199);

    atto_eq(err, HZL_ERR_NULL_PDU);
}

static void
hzlClientTest_ClientBuildRequestCtxMustNotBeNull(void)
{
    hzl_Err_t err;
    hzl_CbsPduMsg_t msgToTx = {0};

    err = hzl_ClientBuildRequest(&msgToTx, NULL, 199);

    atto_eq(err, HZL_ERR_NULL_CTX);
}

static void
hzlClientTest_ClientBuildRequestGroupMustExists(void)
{
    hzl_Err_t err;
    hzl_ClientGroupState_t groupStates[HZL_DEFAULT_TEST_AMOUNT_OF_GROUPS];
    hzl_ClientCtx_t ctx = {
            .clientConfig = &HZL_TEST_CORRECT_CLIENT_CONFIG,
            .groupConfigs = HZL_TEST_CLIENT_CORRECT_GROUP_CONFIGS,
            .groupStates = groupStates,
            .io = HZL_TEST_CORRECT_IO,
    };
    err = hzl_ClientInit(&ctx);
    atto_eq(err, HZL_OK);
    hzl_CbsPduMsg_t msgToTx = {0};

    err = hzl_ClientBuildRequest(&msgToTx, &ctx, 199);

    atto_eq(err, HZL_ERR_UNKNOWN_GROUP);
}

static void
hzlClientTest_ClientBuildRequestSuccessfully(void)
{
    hzl_Err_t err;
    hzl_ClientGroupState_t groupStates[HZL_DEFAULT_TEST_AMOUNT_OF_GROUPS];
    hzl_ClientCtx_t ctx = {
            .clientConfig = &HZL_TEST_CORRECT_CLIENT_CONFIG,
            .groupConfigs = HZL_TEST_CLIENT_CORRECT_GROUP_CONFIGS,
            .groupStates = groupStates,
            .io = HZL_TEST_CORRECT_IO,
    };
    err = hzl_ClientInit(&ctx);
    atto_eq(err, HZL_OK);
    hzl_CbsPduMsg_t msgToTx = {0};
    // Assumption for this test
    atto_eq(ctx.clientConfig->ltk[0], 1);
    atto_zeros(&ctx.clientConfig->ltk[1], 15);

    err = hzl_ClientBuildRequest(&msgToTx, &ctx, 3);
    atto_eq(err, HZL_OK);
    // Transmitted message is a Request
    // Header 0 + reqnonce + tag
    atto_eq(msgToTx.dataLen, 3 + 8 + 16);
    // Packed Header 0
    atto_eq(msgToTx.data[0], 3);  // GID from API call
    atto_eq(msgToTx.data[1], 13);  // SID from client config
    atto_eq(msgToTx.data[2], 2);  // PTY REQ
    // Payload
    // ReqNonce is generated by the TRNG, in this case the dummy TRNG outputting [0,1,2,3,...] etc.
    for (size_t i = 0; i < 8; i++)
    {
        atto_eq(msgToTx.data[3 + i], i);
    }
    const uint8_t expectedTag[16] = {
            0x17, 0x33, 0xB2, 0x99, 0xEF, 0x83, 0x4C, 0x00, 0x14, 0x56,
            0x07, 0x02, 0x5F, 0xE4, 0x33, 0xF0
    };
    atto_memeq(expectedTag, &msgToTx.data[3 + 8], 16);
}

static void
hzlClientTest_ClientBuildRequestIsNotRetransmittedUntilResponseTimeout(void)
{
    hzl_Err_t err;
    hzl_ClientGroupState_t groupStates[HZL_DEFAULT_TEST_AMOUNT_OF_GROUPS];
    hzl_ClientCtx_t ctx = {
            .clientConfig = &HZL_TEST_CORRECT_CLIENT_CONFIG,
            .groupConfigs = HZL_TEST_CLIENT_CORRECT_GROUP_CONFIGS,
            .groupStates = groupStates,
            .io = HZL_TEST_CORRECT_IO,
    };
    err = hzl_ClientInit(&ctx);
    atto_eq(err, HZL_OK);
    hzl_CbsPduMsg_t msgToTx = {0};
    atto_eq(ctx.groupStates[2].lastHandshakeEventInstant, 0);

    err = hzl_ClientBuildRequest(&msgToTx, &ctx, 3);
    atto_eq(err, HZL_OK);
    // Transmitted message is a Request
    // Packed Header 0
    atto_eq(msgToTx.data[0], 3);  // GID from API call
    atto_eq(msgToTx.data[1], 13);  // SID from client config
    atto_eq(msgToTx.data[2], 2);  // PTY REQ
    // Timestamp of Req TX is updated to dummy value
    atto_gt(ctx.groupStates[2].lastHandshakeEventInstant, 42);
    hzl_Timestamp_t previousTimestamp = ctx.groupStates[2].lastHandshakeEventInstant;

    // Transmit a second message to see that a second Request is NOT transmitted
    err = hzl_ClientBuildRequest(&msgToTx, &ctx, 3);
    atto_eq(err, HZL_ERR_HANDSHAKE_ONGOING);
    atto_eq(ctx.groupStates[2].lastHandshakeEventInstant,
            previousTimestamp);  // Timestamp of Req TX is NOT updated

    // Make the timeout expire and now the retransmission of the request can be done
    for (size_t i = 0; i < 500; i++)
    {
        hzlTest_IoMockupCurrentTimeSucceeding(NULL);
    }
    err = hzl_ClientBuildRequest(&msgToTx, &ctx, 3);
    atto_eq(err, HZL_OK);
    atto_gt(ctx.groupStates[2].lastHandshakeEventInstant,
            previousTimestamp);  // Timestamp of Req TX IS updated
}

static void
hzlClientTest_ClientBuildRequestFailingTrng(void)
{
    hzl_Err_t err;
    hzl_ClientGroupState_t groupStates[HZL_DEFAULT_TEST_AMOUNT_OF_GROUPS];
    hzl_ClientCtx_t ctx = {
            .clientConfig = &HZL_TEST_CORRECT_CLIENT_CONFIG,
            .groupConfigs = HZL_TEST_CLIENT_CORRECT_GROUP_CONFIGS,
            .groupStates = groupStates,
            .io = {
                    .trng = hzlTest_IoMockupTrngFailing,
                    .currentTime = hzlTest_IoMockupCurrentTimeSucceeding,
            },
    };
    err = hzl_ClientInit(&ctx);
    atto_eq(err, HZL_OK);
    hzl_CbsPduMsg_t msgToTx = {0};

    err = hzl_ClientBuildRequest(&msgToTx, &ctx, 3);

    atto_eq(err, HZL_ERR_CANNOT_GENERATE_RANDOM);
}

static void
hzlClientTest_ClientBuildRequestFailingTrngAllZeros(void)
{
    hzl_Err_t err;
    hzl_ClientGroupState_t groupStates[HZL_DEFAULT_TEST_AMOUNT_OF_GROUPS];
    hzl_ClientCtx_t ctx = {
            .clientConfig = &HZL_TEST_CORRECT_CLIENT_CONFIG,
            .groupConfigs = HZL_TEST_CLIENT_CORRECT_GROUP_CONFIGS,
            .groupStates = groupStates,
            .io = {
                    .trng = hzlTest_IoMockupTrngFailingJustZeros,
                    .currentTime = hzlTest_IoMockupCurrentTimeSucceeding,
            },
    };
    err = hzl_ClientInit(&ctx);
    atto_eq(err, HZL_OK);
    hzl_CbsPduMsg_t msgToTx = {0};

    err = hzl_ClientBuildRequest(&msgToTx, &ctx, 3);

    atto_eq(err, HZL_ERR_CANNOT_GENERATE_NON_ZERO_RANDOM);
}

static void
hzlClientTest_ClientBuildRequestFailingCurrentTime(void)
{
    hzl_Err_t err;
    hzl_ClientGroupState_t groupStates[HZL_DEFAULT_TEST_AMOUNT_OF_GROUPS];
    hzl_ClientCtx_t ctx = {
            .clientConfig = &HZL_TEST_CORRECT_CLIENT_CONFIG,
            .groupConfigs = HZL_TEST_CLIENT_CORRECT_GROUP_CONFIGS,
            .groupStates = groupStates,
            .io = {
                    .trng = hzlTest_IoMockupTrngSucceeding,
                    .currentTime = hzlTest_IoMockupCurrentTimeFailing,
            },
    };
    err = hzl_ClientInit(&ctx);
    atto_eq(err, HZL_OK);
    hzl_CbsPduMsg_t msgToTx = {0};

    err = hzl_ClientBuildRequest(&msgToTx, &ctx, 3);

    atto_eq(err, HZL_ERR_CANNOT_GET_CURRENT_TIME);
}

void hzlClientTest_ClientBuildRequest(void)
{
    hzlClientTest_ClientBuildRequestMsgToTxMustNotBeNull();
    hzlClientTest_ClientBuildRequestCtxMustNotBeNull();
    hzlClientTest_ClientBuildRequestGroupMustExists();
    hzlClientTest_ClientBuildRequestSuccessfully();
    hzlClientTest_ClientBuildRequestIsNotRetransmittedUntilResponseTimeout();
    hzlClientTest_ClientBuildRequestFailingTrng();
    hzlClientTest_ClientBuildRequestFailingTrngAllZeros();
    hzlClientTest_ClientBuildRequestFailingCurrentTime();
    HZL_TEST_PARTIAL_REPORT();
}
